# Завдання 1

In [1]:
import numpy as np
vector = np.arange(1, 21)
vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [3]:
matrix = np.ones((4, 4))
matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
matrix2 = np.random.uniform(-1, 1, (5, 5))
matrix2

array([[-0.31456047,  0.32955905,  0.35103179, -0.38383307, -0.58760132],
       [ 0.30814067, -0.43864588,  0.99835469, -0.81489385,  0.72583594],
       [ 0.75118976, -0.58836139, -0.92430647,  0.37651042,  0.04498081],
       [-0.19315333,  0.56151368, -0.12615579,  0.08023533, -0.5942924 ],
       [ 0.67724993, -0.35828646,  0.36408682, -0.83104968, -0.90833673]])

In [5]:
matrix3 = np.random.uniform(0, 1, (3, 3))
matrix3

array([[0.66522749, 0.56323925, 0.47903819],
       [0.59714932, 0.33962919, 0.37136216],
       [0.93862206, 0.31699676, 0.33757235]])

In [6]:
array1 = np.random.randint(1, 21, 6)
array2 = np.random.randint(1, 21, 6)


print("Масив 1:", array1)
print("Масив 2:", array2)


sum_result = array1 + array2
subtract_result = array1 - array2
multiply_result = array1 * array2


print("Додавання:", sum_result)
print("Віднімання:", subtract_result)
print("Множення:", multiply_result)

Масив 1: [19  6  1  8  3 11]
Масив 2: [19 11  2 18  4 10]
Додавання: [38 17  3 26  7 21]
Віднімання: [  0  -5  -1 -10  -1   1]
Множення: [361  66   2 144  12 110]


In [11]:
matrix1 = np.random.randint(1, 6, (3, 2))
matrix2 = np.random.randint(1, 6, (2, 4))

print("Матриця 1:", matrix1,sep="\n")

print("Матриця 2:",matrix2,sep="\n")

result = np.dot(matrix1, matrix2)
result

Матриця 1:
[[4 1]
 [5 1]
 [4 4]]
Матриця 2:
[[4 3 3 5]
 [3 5 1 1]]


array([[19, 17, 13, 21],
       [23, 20, 16, 26],
       [28, 32, 16, 24]])

In [12]:
matrix = np.random.uniform(0, 1, (3, 3))
print(np.transpose(matrix))

[[0.09405506 0.89985623 0.49760654]
 [0.83078073 0.08269336 0.24951935]
 [0.54761382 0.31368762 0.76973314]]


In [15]:
matrix1 = np.random.randint(1, 11, (3, 3))

matrix2 = np.random.randint(1, 11, (3, 3))

print("Матриця 1:", matrix1,sep="\n")

print("Матриця 2:",matrix2,sep="\n")

difference = matrix1 - matrix2
difference

Матриця 1:
[[ 9 10  2]
 [ 4  7  4]
 [ 7 10  8]]
Матриця 2:
[[ 9 10  4]
 [ 4  8  8]
 [ 1 10 10]]


array([[ 0,  0, -2],
       [ 0, -1, -4],
       [ 6,  0, -2]])

In [18]:
matrix1 = np.random.randint(-5, 6, (3, 3))

matrix2 = np.random.randint(-5, 6, (3, 3))

print("Матриця 1:", matrix1,sep="\n")

print("Матриця 2:",matrix2,sep="\n")

mult = matrix1 * matrix2
mult

Матриця 1:
[[ 3 -5 -1]
 [-1 -5 -4]
 [-2  5  0]]
Матриця 2:
[[ 3  5 -3]
 [-2  2  2]
 [ 5  5  1]]


array([[  9, -25,   3],
       [  2, -10,  -8],
       [-10,  25,   0]])

In [19]:
matrix = np.random.uniform(-1, 1, (3, 3))

print("Початкова матриця:")
print(matrix)

row_sums = np.sum(matrix, axis=1, keepdims=True)
row_sums

Початкова матриця:
[[-0.1875442   0.99035708  0.58502814]
 [-0.00116089  0.6308947  -0.15998896]
 [ 0.11287582 -0.13055586  0.34344203]]


array([[1.38784102],
       [0.46974485],
       [0.32576198]])

# Завдання 2

In [52]:
import pandas as pd

url = "https://uk.wikipedia.org/wiki/%D0%9D%D0%B0%D1%80%D0%BE%D0%B4%D0%B6%D1%83%D0%B2%D0%B0%D0%BD%D1%96%D1%81%D1%82%D1%8C_%D0%B2_%D0%A3%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%96"

tables = pd.read_html(url)

target_table = tables[20]
print(target_table)

                       регіон   1950   1960   1970  1990  1992  1994  1996  \
0   Автономна Республіка Крим  230.0  206.0  160.0   130   109    93    80   
1           Вінницька область  224.0  192.0  142.0   124   119   107   103   
2           Волинська область  247.0  250.0  179.0   153   150   137   125   
3    Дніпропетровська область  204.0  204.0  151.0   123   106    92    80   
4            Донецька область  271.0  214.0  140.0   109    94    82    70   
5         Житомирська область  261.0  223.0  159.0   129   128   118   108   
6        Закарпатська область  314.0  273.0  207.0   168   161   138   128   
7          Запорізька область  219.0  197.0  150.0   124   107    92    81   
8   Івано-Франківська область  243.0  248.0  182.0   155   144   131   122   
9            Київська область  204.0  189.0  156.0   123   111    99    92   
10     Кіровоградська область  216.0  171.0  145.0   126   119   107    96   
11          Луганська область  262.0  235.0  144.0   116   101  

In [47]:
target_table.head()

регіон   1950   1960   1970  1990  1992  1994  1996  \
0  Автономна Республіка Крим  230.0  206.0  160.0   130   109    93    80   
1          Вінницька область  224.0  192.0  142.0   124   119   107   103   
2          Волинська область  247.0  250.0  179.0   153   150   137   125   
3   Дніпропетровська область  204.0  204.0  151.0   123   106    92    80   
4           Донецька область  271.0  214.0  140.0   109    94    82    70   

   2000  2004  2008  2012   2014  
0    73    90   119   126    NaN  
1    84    90   108   112  109.0  
2   112   119   148   148  141.0  
3    71    89   110   112  111.0  
4    61    76    98    98   82.0

In [57]:
df = pd.DataFrame(target_table)
shape = df.shape
print("Кількість рядків і стовпців:", shape)

Кількість рядків і стовпців: (28, 13)


In [59]:
df.replace(np.nan,'—', inplace=True)
df

регіон   1950   1960   1970  1990  1992  1994  1996  \
0   Автономна Республіка Крим  230.0  206.0  160.0   130   109    93    80   
1           Вінницька область  224.0  192.0  142.0   124   119   107   103   
2           Волинська область  247.0  250.0  179.0   153   150   137   125   
3    Дніпропетровська область  204.0  204.0  151.0   123   106    92    80   
4            Донецька область  271.0  214.0  140.0   109    94    82    70   
5         Житомирська область  261.0  223.0  159.0   129   128   118   108   
6        Закарпатська область  314.0  273.0  207.0   168   161   138   128   
7          Запорізька область  219.0  197.0  150.0   124   107    92    81   
8   Івано-Франківська область  243.0  248.0  182.0   155   144   131   122   
9            Київська область  204.0  189.0  156.0   123   111    99    92   
10     Кіровоградська область  216.0  171.0  145.0   126   119   107    96   
11          Луганська область  262.0  235.0  144.0   116   101    84    72   
12          Львівська область  234.0  240.0  171.0   140   132   117   111   
13       Миколаївська область  211.0  194.0  155.0   137   123   107    96   
14            Одеська область  241.0  192.0  148.0   126   114   100    92   
15         Полтавська область  186.0  163.0  131.0   118   108    95    88   
16         Рівненська область  269.0  267.0  193.0   158   154   145   132   
17            Сумська область  216.0  184.0  132.0   115   105    92    84   
18      Тернопільська область  213.0  216.0  157.0   142   138   123   115   
19         Харківська область  197.0  173.0  140.0   114    98    83    76   
20         Херсонська область  208.0  214.0  166.0   143   130   111    98   
21        Хмельницька область  234.0  198.0  148.0   129   124   111   106   
22          Черкаська область  205.0  179.0  144.0   123   114   100    93   
23        Чернівецька область  247.0  218.0  170.0   148   140   128   121   
24       Чернігівська область  220.0  183.0  127.0   108    98    88    82   
25                       Київ      —  174.0  159.0   120    97    81    76   
26    Севастополь (міськрада)      —      —      —   125    96    76    69   
27                    Україна  228.0  205.0  152.0   126   114   100    92   

    2000  2004  2008  2012   2014  
0     73    90   119   126      —  
1     84    90   108   112  109.0  
2    112   119   148   148  141.0  
3     71    89   110   112  111.0  
4     61    76    98    98   82.0  
5     89    98   113   122  120.0  
6    115   124   147   151  146.0  
7     71    85   103   106  106.0  
8    103   107   123   124  122.0  
9     73    90   117   122  121.0  
10    79    86   102   110  108.0  
11    62    73    95    96   51.0  
12    91   101   113   119  119.0  
13    80    90   112   115  112.0  
14    80    96   120   127  123.0  
15    70    75    97    99  100.0  
16   118   125   148   159  148.0  
17    70    72    91    97   92.0  
18    92    99   113   113  109.0  
19    68    80    98    99  101.0  
20    85    91   113   117  115.0  
21    85    91   110   113  112.0  
22    75    77    95   100   98.0  
23   101   106   122   128  129.0  
24    69    75    89    94   90.0  
25    73    98   116   120  121.0  
26    70    97   110   120      —  
27    78    90   110   114  108.0

In [60]:
column_types = df.dtypes

print("Типи стовпців:")
print(column_types)

Типи стовпців:
регіон    object
1950      object
1960      object
1970      object
1990       int64
1992       int64
1994       int64
1996       int64
2000       int64
2004       int64
2008       int64
2012       int64
2014      object
dtype: object


In [101]:
non_numeric_columns = df.select_dtypes(exclude=[np.number]).columns
column_to_remove = 'регіон'
on_numeric_columns = non_numeric_columns.drop(column_to_remove, errors='ignore')
print(on_numeric_columns)
df['1950']=pd.to_numeric(df['1950'],errors='coerce')
df['1960']=pd.to_numeric(df['1960'],errors='coerce')
df['1970']=pd.to_numeric(df['1970'],errors='coerce')
df['2014']=pd.to_numeric(df['2014'],errors='coerce')
column_types = df.dtypes
print(column_types)

Index(['1960'], dtype='object')
регіон     object
1950      float64
1960      float64
1970      float64
1990        int64
1992        int64
1994        int64
1996        int64
2000        int64
2004        int64
2008        int64
2012        int64
2014      float64
dtype: object


In [103]:
missing_counts = df.isnull().sum()

print("Кількість пропущених значень у кожному стовпці:")
print(missing_counts)

Кількість пропущених значень у кожному стовпці:
регіон    0
1950      2
1960      1
1970      1
1990      0
1992      0
1994      0
1996      0
2000      0
2004      0
2008      0
2012      0
2014      2
dtype: int64


In [104]:
df = df.drop(df.index[-1])
df

регіон   1950   1960   1970  1990  1992  1994  1996  \
0   Автономна Республіка Крим  230.0  206.0  160.0   130   109    93    80   
1           Вінницька область  224.0  192.0  142.0   124   119   107   103   
2           Волинська область  247.0  250.0  179.0   153   150   137   125   
3    Дніпропетровська область  204.0  204.0  151.0   123   106    92    80   
4            Донецька область  271.0  214.0  140.0   109    94    82    70   
5         Житомирська область  261.0  223.0  159.0   129   128   118   108   
6        Закарпатська область  314.0  273.0  207.0   168   161   138   128   
7          Запорізька область  219.0  197.0  150.0   124   107    92    81   
8   Івано-Франківська область  243.0  248.0  182.0   155   144   131   122   
9            Київська область  204.0  189.0  156.0   123   111    99    92   
10     Кіровоградська область  216.0  171.0  145.0   126   119   107    96   
11          Луганська область  262.0  235.0  144.0   116   101    84    72   
12          Львівська область  234.0  240.0  171.0   140   132   117   111   
13       Миколаївська область  211.0  194.0  155.0   137   123   107    96   
14            Одеська область  241.0  192.0  148.0   126   114   100    92   
15         Полтавська область  186.0  163.0  131.0   118   108    95    88   
16         Рівненська область  269.0  267.0  193.0   158   154   145   132   
17            Сумська область  216.0  184.0  132.0   115   105    92    84   
18      Тернопільська область  213.0  216.0  157.0   142   138   123   115   
19         Харківська область  197.0  173.0  140.0   114    98    83    76   
20         Херсонська область  208.0  214.0  166.0   143   130   111    98   
21        Хмельницька область  234.0  198.0  148.0   129   124   111   106   
22          Черкаська область  205.0  179.0  144.0   123   114   100    93   
23        Чернівецька область  247.0  218.0  170.0   148   140   128   121   
24       Чернігівська область  220.0  183.0  127.0   108    98    88    82   
25                       Київ    NaN  174.0  159.0   120    97    81    76   
26    Севастополь (міськрада)    NaN    NaN    NaN   125    96    76    69   

    2000  2004  2008  2012   2014  
0     73    90   119   126    NaN  
1     84    90   108   112  109.0  
2    112   119   148   148  141.0  
3     71    89   110   112  111.0  
4     61    76    98    98   82.0  
5     89    98   113   122  120.0  
6    115   124   147   151  146.0  
7     71    85   103   106  106.0  
8    103   107   123   124  122.0  
9     73    90   117   122  121.0  
10    79    86   102   110  108.0  
11    62    73    95    96   51.0  
12    91   101   113   119  119.0  
13    80    90   112   115  112.0  
14    80    96   120   127  123.0  
15    70    75    97    99  100.0  
16   118   125   148   159  148.0  
17    70    72    91    97   92.0  
18    92    99   113   113  109.0  
19    68    80    98    99  101.0  
20    85    91   113   117  115.0  
21    85    91   110   113  112.0  
22    75    77    95   100   98.0  
23   101   106   122   128  129.0  
24    69    75    89    94   90.0  
25    73    98   116   120  121.0  
26    70    97   110   120    NaN

In [105]:
df = df.fillna(df.mean())
df

C:\Users\faika\AppData\Local\Temp/ipykernel_27392/983163164.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df = df.fillna(df.mean())


регіон    1950        1960   1970  1990  1992  1994  \
0   Автономна Республіка Крим  230.00  206.000000  160.0   130   109    93   
1           Вінницька область  224.00  192.000000  142.0   124   119   107   
2           Волинська область  247.00  250.000000  179.0   153   150   137   
3    Дніпропетровська область  204.00  204.000000  151.0   123   106    92   
4            Донецька область  271.00  214.000000  140.0   109    94    82   
5         Житомирська область  261.00  223.000000  159.0   129   128   118   
6        Закарпатська область  314.00  273.000000  207.0   168   161   138   
7          Запорізька область  219.00  197.000000  150.0   124   107    92   
8   Івано-Франківська область  243.00  248.000000  182.0   155   144   131   
9            Київська область  204.00  189.000000  156.0   123   111    99   
10     Кіровоградська область  216.00  171.000000  145.0   126   119   107   
11          Луганська область  262.00  235.000000  144.0   116   101    84   
12          Львівська область  234.00  240.000000  171.0   140   132   117   
13       Миколаївська область  211.00  194.000000  155.0   137   123   107   
14            Одеська область  241.00  192.000000  148.0   126   114   100   
15         Полтавська область  186.00  163.000000  131.0   118   108    95   
16         Рівненська область  269.00  267.000000  193.0   158   154   145   
17            Сумська область  216.00  184.000000  132.0   115   105    92   
18      Тернопільська область  213.00  216.000000  157.0   142   138   123   
19         Харківська область  197.00  173.000000  140.0   114    98    83   
20         Херсонська область  208.00  214.000000  166.0   143   130   111   
21        Хмельницька область  234.00  198.000000  148.0   129   124   111   
22          Черкаська область  205.00  179.000000  144.0   123   114   100   
23        Чернівецька область  247.00  218.000000  170.0   148   140   128   
24       Чернігівська область  220.00  183.000000  127.0   108    98    88   
25                       Київ  231.04  174.000000  159.0   120    97    81   
26    Севастополь (міськрада)  231.04  207.576923  156.0   125    96    76   

    1996  2000  2004  2008  2012    2014  
0     80    73    90   119   126  111.44  
1    103    84    90   108   112  109.00  
2    125   112   119   148   148  141.00  
3     80    71    89   110   112  111.00  
4     70    61    76    98    98   82.00  
5    108    89    98   113   122  120.00  
6    128   115   124   147   151  146.00  
7     81    71    85   103   106  106.00  
8    122   103   107   123   124  122.00  
9     92    73    90   117   122  121.00  
10    96    79    86   102   110  108.00  
11    72    62    73    95    96   51.00  
12   111    91   101   113   119  119.00  
13    96    80    90   112   115  112.00  
14    92    80    96   120   127  123.00  
15    88    70    75    97    99  100.00  
16   132   118   125   148   159  148.00  
17    84    70    72    91    97   92.00  
18   115    92    99   113   113  109.00  
19    76    68    80    98    99  101.00  
20    98    85    91   113   117  115.00  
21   106    85    91   110   113  112.00  
22    93    75    77    95   100   98.00  
23   121   101   106   122   128  129.00  
24    82    69    75    89    94   90.00  
25    76    73    98   116   120  121.00  
26    69    70    97   110   120  111.44

In [111]:
average_birth_rate_2014 = df['2014'].mean()
regions_with_higher_birth_rate = df[df['2014'] > average_birth_rate_2014]
region_list = regions_with_higher_birth_rate['регіон'].tolist()
print(region_list)

['Волинська область', 'Житомирська область', 'Закарпатська область', 'Івано-Франківська область', 'Київська область', 'Львівська область', 'Миколаївська область', 'Одеська область', 'Рівненська область', 'Херсонська область', 'Хмельницька область', 'Чернівецька область', 'Київ']


In [138]:
max_2012=df['2012'].max()
max_2008=df['2008'].max()
reg_2012 = df[df['2012']==max_2012]["регіон"].tolist()
reg_2008 = df[df['2008']==max_2008]["регіон"].tolist()
print("Максимальна народжуваність в 2012:",reg_2012[0])
print("Максимальна народжуваність в 2008:",reg_2008[0])

Максимальна народжуваність в 2012: Рівненська область
Максимальна народжуваність в 2008: Волинська область


In [139]:
import matplotlib.pyplot as plt
plt.figure(figsize=(10, 6))  
plt.bar(df['регіон'], df['2014'], color='skyblue') 
plt.xlabel('Регіон')  
plt.ylabel('Народжуваність в 2014 році') 
plt.title('Народжуваність за регіонами в 2014 році') 
plt.xticks(rotation=45, ha='right') 
plt.tight_layout()  
plt.show() 